name: Ejecutar pruebas Serenity BDD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-serenity-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Gradle Cache
        uses: gradle/gradle-build-action@v3

      - name: Dar permisos a gradlew
        run: chmod +x gradlew

      - name: Verificar conectividad a fakestoreapi.com
        run: curl -I https://fakestoreapi.com/products || true

      - name: Ejecutar pruebas con Gradle
        run: ./gradlew clean test --info
        env:
          GRADLE_OPTS: '-Xmx1024m'

      - name: Mostrar errores si fallan las pruebas
        if: failure()
        run: |
          echo "==== CONTENIDO DE TEST REPORT ===="
          cat build/reports/tests/test/index.html || echo "No se pudo leer el reporte HTML"
          echo "==== FIN DE REPORTE ===="

      - name: Comprimir reporte Serenity
        run: zip -r SerenityReports.zip target/site/serenity

      - name: Subir reporte Serenity como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: SerenityReports
          path: SerenityReports.zip

      - name: Subir reporte de fallos de tests
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: TestReport
          path: build/reports/tests